### get all accounts
GET http://localhost:4004/service-catalog/account HTTP/1.1

### get single account
GET http://localhost:4004/service-catalog/account(id=1,IsActiveEntity=true)/image HTTP/1.1

###
GET http://localhost:4004/service-catalog/Currencies HTTP/1.1

###

POST http://localhost:4004/service-catalog/account HTTP/1.1
Content-Type: application/json

{
    "id": 5,
    "title": "wallet",
    "descr": "wallet account",
    "status": true,
    "currency_code": "PKR" 
}

###
GET http://localhost:4004/service-catalog/Attachments
Content-Type: application/json
###
GET http://localhost:4004/service-catalog/Attachments(c7bf7168-0e30-48d6-aed2-6355d3effb16)
Content-Type: application/json